### PR TITLE
fibonacci series in C

### PR DESCRIPTION
**Pull request by rishikasoni67**

### CODE REVIEW

**Comment by Chirag-Mathur** [comment]
@rishikasoni67 I think you have deleted the code in the last commit.

**Comment by rishikasoni67** [comment]
> @rishikasoni67 I think you have deleted the code in the last commit.

It was by mistake ( I am new to github)

**Comment by Chirag-Mathur** [comment]
@rishikasoni67 Add the snapshot of input and output

**Comment by rishikasoni67** [comment]
> @rishikasoni67 Add the snapshot of input and output
Input :
Screenshot_Input_fibonacciSeries
Output :
Screenshot_Output

**Pull request merged**
