### PR TITLE
Create GrakinForces folder

### PR DESCRIPTION
**Pull request by priyanshupardhi**
Closes issue #33

### CODE REVIEW

**Comment by Chirag-Mathur** [comment]
@priyanshupardhi  Add a basic text file having the description of the folder inside the GrakinForces folder

**Comment by priyanshupardhi** [comment]
@Chirag-Mathur should I have to make PR again?

**Comment by Chirag-Mathur** [comment]
Push the commit in this pr only

**Comment by priyanshupardhi** [comment]
Thank you @Chirag-Mathur

**Pull request merged**
