### PR TITLE
added folder and file for CF Round 673-Div2 674-Div3 Grankforces

### PR DESCRIPTION
**Pull request by sachin-611**
resolved all the issues :)

### CODE REVIEW

**Comment by sachin-611** [comment]
@Chirag-Mathur please look into it

**Review by Chirag-Mathur — CHANGES_REQUESTED** [review]
Remove the .exe file.
Rest is all is great.
@sachin-611 Good Work 👍

**Comment by sachin-611** [comment]
@Chirag-Mathur is it fine now? made the changes that you demanded.
Thank you :)

**Review by Chirag-Mathur — APPROVED** [review]

**Comment by Chirag-Mathur** [comment]
@sachin-611 LGTM 👍

**Pull request merged**
