### PR TITLE
Create BHPORSRP.py

### PR DESCRIPTION
**Pull request by Shreyansh-Mishra**

### CODE REVIEW

**Comment by Chirag-Mathur** [comment]
@Shreyansh-Mishra Add the link of codechef submission

**Comment by Shreyansh-Mishra** [comment]
[https://www.codechef.com/viewsolution/36108980](url)

**Comment by Chirag-Mathur** [comment]
@Shreyansh-Mishra Add the screenshot as link is not working.

**Comment by Shreyansh-Mishra** [comment]
Please check correctly, it is working. Maybe your browser is broke.

**Comment by Chirag-Mathur** [comment]
@Shreyansh-Mishra LGTM 👍

**Pull request merged**
